Traceback (most recent call last):
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib
matplotlib.rcParams['mathtext.fontset'] = 'stix'
matplotlib.rcParams['font.family'] = 'STIXGeneral'

import schemdraw
import schemdraw.elements as elm
with schemdraw.Drawing(file='mesh-toy-problem.svg') as d:
    d += (Vs := elm.SourceV().up().label('$V_S$\n5 V'))
    d += (R1 := elm.Resistor().right().label('$R_1$\n6'))
    d += (R3 := elm.Resistor().right().label('$R_3$\n14'))
    d += (R2 := elm.Resistor().at(R1.end).down().label('$R_2$\n24'))
    d += (R4 := elm.Resistor().at(R3.end).down().label('$R_4$\10'))
    d += elm.Line().left().tox(R1.start)
    d += elm.GroundSignal()
------------------

Traceback [1;36m(most recent call last)[0m:

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\IPython\core\interactiveshell.py:3433[0m in [0;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0m  Cell [0;32mIn [4], line 7[0m
    with schemdraw.Drawing(file='mesh-toy-problem.svg') as d:[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\schemdraw.py:176[0m in [0;35m__exit__[0m
    self.save(self.outfile)[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\schemdraw.py:389[0m in [0;35msave[0m
    self.draw(show=False)[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\schemdraw.py:364[0m in [0;35mdraw[0m
    self._initfig(ax=ax, backend=backend, showframe=showframe)[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\schemdraw.py:340[0m in [0;35m_initfig[0m
    bbox=self.get_bbox(),[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\schemdraw.py:196[0m in [0;35mget_bbox[0m
    bbox = element.get_bbox(transform=True)[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\elements\elements.py:414[0m in [0;35mget_bbox[0m
    segxmin, segymin, segxmax, segymax = segment.get_bbox()[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\segments.py:333[0m in [0;35mget_bbox[0m
    w, h, _ = svg.text_size(self.text, 'Arial', self.fontsize)[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\backends\svg.py:178[0m in [0;35mtext_size[0m
    textsize = svgtext.text_approx_size(text, font=font, size=size)[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\backends\svgtext.py:306[0m in [0;35mtext_approx_size[0m
    math = ' '.join(mathtextsvg(line).itertext())  # itertext strips all the tags[0m

[0m  File [0;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\schemdraw\backends\svgtext.py:234[0m in [0;35mmathtextsvg[0m
    return ET.fromstring(svgtext)[0m

[1;36m  File [1;32mC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py:1342[1;36m in [1;35mXML[1;36m
[1;33m    parser.feed(text)[1;36m

[1;36m  File [1;32m<string>[1;36m[0m
[1;31mParseError[0m[1;31m:[0m not well-formed (invalid token): line 1, column 9

ParseError: not well-formed (invalid token): line 1, column 9 (<string>)

